## Santander Coders Exercises from Class #2 Unit #2

Data: 07/02/2024. De: Ada Tech. Language: Portuguese.

In [5]:
import numpy as np
import random

## Exercícios 
Utilize comprehension para gerar a lista de todos os números inteiros entre 0 e 19. Converta a lista em um numpy array bidimensional(matriz) com 4 linhas e 5 colunas.

In [6]:
listaNumeros = [num for num in range(20)]

arrayBidimensional = np.array(listaNumeros).reshape(4,5) ##USANDO A FUNÇÃI Reshape para reorganizar as dimensões de 4 linhas e 5 colunas como foi pedido

print("Array bidimensional: ")
print(arrayBidimensional)



Array bidimensional: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz A com 5 linhas e 6 colunas.

In [28]:

numeros = random.sample(range(1,50), 30)

print("Array Unidimensional")
print(numeros)


matrizA = np.array(numeros).reshape(5,6)
print("\n\nArray Unidimensaional")
print(matrizA)



Array Unidimensional
[6, 37, 38, 24, 44, 34, 4, 45, 10, 14, 12, 17, 40, 15, 22, 49, 16, 47, 29, 8, 27, 31, 13, 30, 7, 42, 43, 23, 20, 35]


Array Unidimensaional
[[ 6 37 38 24 44 34]
 [ 4 45 10 14 12 17]
 [40 15 22 49 16 47]
 [29  8 27 31 13 30]
 [ 7 42 43 23 20 35]]


Construa um array A bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20.

    faça uma cópia do array A criado, chamando a cópia de Ac
    Substitua todos os elementos do array A que sejam maiores que 10 pelo valor -1
    Substitua todos os elementos do array Ac que sejam maiores que 7 e menores que 15 pelo valor -1
    Dica: Gere máscaras booleanas para realizar as modificações nos arrays.

In [37]:
array_A = np.random.randint(0,21, size=(5,6))

array_Ac = array_A.copy()

array_A[array_A > 10] = -1
array_Ac[(array_Ac > 7) & (array_Ac < 15)] = -1

print("Array A:")
print(array_A)
print("\n\nArray Ac:")
print(array_Ac)

Array A:
[[ 9  7  4 -1 -1  5]
 [ 6 -1 -1  5 -1 10]
 [-1 -1 -1 -1  5  6]
 [ 0 -1 -1 -1  4  3]
 [ 6 -1  7 -1  2 -1]]


Array Ac:
[[-1  7  4 16 15  5]
 [ 6 17 19  5 16 -1]
 [16 15 17 17  5  6]
 [ 0 -1 20 -1  4  3]
 [ 6 -1  7 19  2 -1]]


Construa um array A com 20 linhas e 10 colunas onde os elementos são os números interios de 1 até 200.

    Crie uma view de A chamada A_lpares contendo apenas as linhas de A com índice par.
    Crie uma view de A chamada A_lpares_cimpares contendo as linhas A com índice par e colunas com índice ímpar.

In [38]:
array_A2 = np.arange(1,201).reshape(20,10)

A_lpares = array_A2[::2] ##INDICE PAR
A_lpares_cimpares = array_A2[::2, 1::2] ##Linhas com indice par e colunas com indice impar

print("Array A:")
print(array_A2)
print("\n\nView A_lpares:")
print(A_lpares)
print("\n\nView A_lpares_cimpares:")
print(A_lpares_cimpares)


Array A:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]
 [191 192 193 194 195 196 197 198 199 200]]


View A_lpares:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 41  42  43  44  45  46  

Substitua os elememtos do array A do exercício anterior por -1 quando pelo menos um dos índices do elemento é par.

Dica: Construa uma máscara booleana

In [43]:
array_A3 = np.arange(1,201).reshape(20,10)

mascaraLinhas = np.arange(array_A3.shape[0]) % 2 == 0

mascaraColunas = np.arange(array_A3.shape[1]) % 2 == 0

mascara = mascaraLinhas[:, np.newaxis] | mascaraColunas


array_A3[mascara] = -1

print("Array A:")
print(array_A3)

Array A:
[[ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  12  -1  14  -1  16  -1  18  -1  20]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  32  -1  34  -1  36  -1  38  -1  40]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  52  -1  54  -1  56  -1  58  -1  60]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  72  -1  74  -1  76  -1  78  -1  80]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  92  -1  94  -1  96  -1  98  -1 100]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 112  -1 114  -1 116  -1 118  -1 120]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 132  -1 134  -1 136  -1 138  -1 140]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 152  -1 154  -1 156  -1 158  -1 160]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 172  -1 174  -1 176  -1 178  -1 180]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 192  -1 194  -1 196  -1 198  -1 200]]


Construa uma função chamada ordena_linhas que recebe uma matriz como parâmetro e troque as linhas de posição para que fiquem ordenadas de acordo com a primeira coluna. Por exemplo:

A = np.array([[20, 26, 12], 
              [8, 3, 26], 
              [3, 10, 4]])
print(ordena_linhas(A))
deve resultar em

[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]

In [44]:
def ordenarLinhas(matriz):
    indicesOrdenados = np.argsort(matriz[:,0])
    matrizOrdenadas = matriz[indicesOrdenados]
    return matrizOrdenadas

A = np.array([[20,26,12],
              [8,3,26],
              [3,10,4]])

print(ordenarLinhas(A))

[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]
