## Santander Coders Exercises from Class #2 Unit #2

Data: 07/02/2024. De: Ada Tech. Language: Portuguese.

In [5]:
import numpy as np
import random

## Exercícios 
Utilize comprehension para gerar a lista de todos os números inteiros entre 0 e 19. Converta a lista em um numpy array bidimensional(matriz) com 4 linhas e 5 colunas.

In [6]:
listaNumeros = [num for num in range(20)]

arrayBidimensional = np.array(listaNumeros).reshape(4,5) ##USANDO A FUNÇÃI Reshape para reorganizar as dimensões de 4 linhas e 5 colunas como foi pedido

print("Array bidimensional: ")
print(arrayBidimensional)



Array bidimensional: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz A com 5 linhas e 6 colunas.

In [28]:

numeros = random.sample(range(1,50), 30)

print("Array Unidimensional")
print(numeros)


matrizA = np.array(numeros).reshape(5,6)
print("\n\nArray Unidimensaional")
print(matrizA)



Array Unidimensional
[6, 37, 38, 24, 44, 34, 4, 45, 10, 14, 12, 17, 40, 15, 22, 49, 16, 47, 29, 8, 27, 31, 13, 30, 7, 42, 43, 23, 20, 35]


Array Unidimensaional
[[ 6 37 38 24 44 34]
 [ 4 45 10 14 12 17]
 [40 15 22 49 16 47]
 [29  8 27 31 13 30]
 [ 7 42 43 23 20 35]]


Construa um array A bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20.

    faça uma cópia do array A criado, chamando a cópia de Ac
    Substitua todos os elementos do array A que sejam maiores que 10 pelo valor -1
    Substitua todos os elementos do array Ac que sejam maiores que 7 e menores que 15 pelo valor -1
    Dica: Gere máscaras booleanas para realizar as modificações nos arrays.

Construa um array A com 20 linhas e 10 colunas onde os elementos são os números interios de 1 até 200.

    Crie uma view de A chamada A_lpares contendo apenas as linhas de A com índice par.
    Crie uma view de A chamada A_lpares_cimpares contendo as linhas A com índice par e colunas com índice ímpar.

Substitua os elememtos do array A do exercício anterior por -1 quando pelo menos um dos índices do elemento é par.

Dica: Construa uma máscara booleana

Construa uma função chamada ordena_linhas que recebe uma matriz como parâmetro e troque as linhas de posição para que fiquem ordenadas de acordo com a primeira coluna. Por exemplo:

A = np.array([[20, 26, 12], 
              [8, 3, 26], 
              [3, 10, 4]])
print(ordena_linhas(A))
deve resultar em

[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]